site:
  about:
    siteName: 2P in Kotlin
    siteDescription: A Kotlin Multiplatform-based ecosystem for logic programming
Editorial:
  primaryColor: '#DE9149'
  social:
    github: 'tuProlog/2p-kt'
  metaComponents:
    - type: 'orchidSearch'
    - type: mermaid
      selector: '.mermaid' # optional
  legacySearch: false
  menu:
    - type: link
      title: Home
      url: '/'
    - type: 'pages'
    - type: "license"
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
wiki:
  sections:
    - 'Rationale and Architecture'
    - 'Developers Guide'
    - 'Users Guide'
  defaultConfig:
    createPdf: true
kotlindoc:
  sourceDirs:
    - '../../../../core/src/commonMain/kotlin'
    - '../../../../unify/src/commonMain/kotlin'
    - '../../../../theory/src/commonMain/kotlin'
    - '../../../../solve/src/commonMain/kotlin'
    - '../../../../solve-classic/src/commonMain/kotlin'
    - '../../../../solve-streams/src/commonMain/kotlin'
    - '../../../../dsl-core/src/commonMain/kotlin'
    - '../../../../dsl-unify/src/commonMain/kotlin'
    - '../../../../dsl-theory/src/commonMain/kotlin'
    - '../../../../solve-parser/src/commonMain/kotlin'
    - '../../../../solve-theory/src/commonMain/kotlin'
  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true
assets:
  compilers:
    binaryExtensions:
      - 'png'
  sourceDirs:
    - 'assets/media'
    - 'assets/diagrams'
    - 'assets/generated'